### ISSUE TITLE
Will the Github Action stop execution on failure?

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat-api#7]
https://github.com/la5nta/pat-api/blob/b801456fcd0569774b48530ec06dc542fc958541/.github/workflows/go.yml#L42

If this fails, do we risk overwriting the current file with an empty one? 🤔

**Comment by xylo04** [comment]
I'm about 70% sure if `go run` fails, it will return with a non-zero exit code, which will cause the entire workflow to fail and we'll get an email about a failed run. It would be worth introducing a problem and see if that's correct.

**Comment by martinhpedersen** [comment]
Just as you predicted 👍
